package com.veterinaria.veterinariaapp.ui;

import com.veterinaria.veterinariaapp.security.SessionManager;
import com.veterinaria.veterinariaapp.service.AuthService;
// --- ¡IMPORTS PARA MAIN! ---
import com.veterinaria.veterinariaapp.repository.IUsuarioRepository;
import com.veterinaria.veterinariaapp.repository.UsuarioRepository;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author JESUS MARIO
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    // --- ¡CORREGIDO! ---
    // private final AuthService auth = new AuthService(); // <-- ELIMINADO
    private final AuthService auth; // <-- AÑADIDO

    // --- ¡CORREGIDO! (Recibe el servicio) ---
    public LoginFrame(AuthService auth) {
        this.auth = auth; // <-- AÑADIDO

        initComponents();
        setTitle("Veterinario - Iniciar sesión");
        setLocationRelativeTo(null);
        txtEmail.setText(""); // Limpiar campos al inicio
        txtPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email:");

        jLabel2.setText("Contraseña:");

        txtEmail.setText("jTextField1");

        txtPass.setText("jPasswordField1");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        btnLogin.setText("Iniciar Sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogin)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel3)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnLogin)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         String email = txtEmail.getText().trim();
         String pass  = new String(txtPass.getPassword());

         if (email.isEmpty() || pass.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Completa email y contraseña.",
                     "Faltan datos", JOptionPane.WARNING_MESSAGE);
             return;
         }
         try {
             // Llama al servicio inyectado
             var user = auth.autenticar(email, pass);

             // Guarda el usuario en la sesión
             SessionManager.get().login(user);

             // Mensaje de bienvenida (opcional)
             // JOptionPane.showMessageDialog(this, "Bienvenido/a, " + user.getNombre());

             // --- ¡ENSAMBLAJE DE MainWindow! ---
             // Aquí creamos MainWindow (que ahora internamente ensambla todo lo demás)
             MainWindow mw = new MainWindow();
             mw.setLocationRelativeTo(null); // Centrarla
             mw.setVisible(true);

             // Cerrar el login
             this.dispose();

         } catch (IllegalArgumentException | IllegalStateException e) { // Captura errores de login específicos
             logger.log(java.util.logging.Level.INFO, "Login fallido para {0}: {1}", new Object[]{email, e.getMessage()});
             JOptionPane.showMessageDialog(this, e.getMessage(),
                     "Error de inicio de sesión", JOptionPane.WARNING_MESSAGE); // WARNING en lugar de ERROR
             txtPass.setText("");
             txtPass.requestFocusInWindow();
         } catch (Exception e) { // Captura otros errores (BD, etc.)
             logger.log(java.util.logging.Level.SEVERE, "Error inesperado en login", e);
             JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado. Contacte al administrador.",
                     "Error Crítico", JOptionPane.ERROR_MESSAGE);
             txtPass.setText("");
             txtPass.requestFocusInWindow();
         }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
             // Usar el look & feel del sistema operativo para mejor apariencia
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo establecer el LookAndFeel del sistema", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // --- ¡ENSAMBLAJE DE AuthService y LoginFrame! ---
            IUsuarioRepository repo = new UsuarioRepository();
            AuthService authService = new AuthService(repo);
            new LoginFrame(authService).setVisible(true); // <-- Inyecta el servicio
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
