/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.veterinaria.veterinariaapp.ui;

/**
 *
 * @author JESUS MARIO
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    private com.veterinaria.veterinariaapp.ui.ClienteViewForm clientesWindow;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        // tamaño inicial y mínimos
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setSize(1200, 700);              // tamaño con el que arrancará

        setTitle("Veterinario - Panel Principal");
        setLocationRelativeTo(null); // centrar

        // ==== Acciones de menú ====
        miCerrarSesion.addActionListener(e -> {
            com.veterinaria.veterinariaapp.security.SessionManager.get().logout();
            javax.swing.JOptionPane.showMessageDialog(this, "Sesión cerrada.");
            new com.veterinaria.veterinariaapp.ui.LoginFrame().setVisible(true);
            dispose();
        });

        miSalir.addActionListener(e -> System.exit(0));

        // Atajos (opcional)
        miCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
                java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
                java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));

        // Módulos clientes para abrir con un JPanel
        miDuenos.addActionListener(e -> {
            // 1) Instancia tu vista existente
           var vista = new com.veterinaria.veterinariaapp.ui.ClienteViewForm();

           // 2) Limpia el panel contenedor
           jPanelClientes.removeAll();
           jPanelClientes.setLayout(new java.awt.BorderLayout());

           // 3) Inserta el contenido del JFrame dentro del panel
           jPanelClientes.add(vista.getContentPane(), java.awt.BorderLayout.CENTER);

           // 4) Refresca
           jPanelClientes.revalidate();
           jPanelClientes.repaint();
        });
        miMascotas.addActionListener(e ->
                javax.swing.JOptionPane.showMessageDialog(this, "Abrir módulo: Mascotas"));
        miCitas.addActionListener(e ->
                javax.swing.JOptionPane.showMessageDialog(this, "Abrir módulo: Citas"));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCerrarSesion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miDuenos = new javax.swing.JMenuItem();
        miMascotas = new javax.swing.JMenuItem();
        miCitas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientes.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Archivo");

        miCerrarSesion.setText("Cerrar Sesión");
        jMenu1.add(miCerrarSesion);

        miSalir.setText("Salir");
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modulos");

        miDuenos.setText("Dueños");
        jMenu2.add(miDuenos);

        miMascotas.setText("Mascotas");
        jMenu2.add(miMascotas);

        miCitas.setText("Citas");
        jMenu2.add(miCitas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JMenuItem miCitas;
    private javax.swing.JMenuItem miDuenos;
    private javax.swing.JMenuItem miMascotas;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
